const {chromium}=require(process.argv[2]||'playwright-core'),fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const data=require('./assets/data.js'),assets=path.join(__dirname,'assets'),out=path.join(__dirname,'test-output-1.3');fs.mkdirSync(out,{recursive:true});
const legacy={version:1,days:{'2026-09-05':{kind:'pt',exercises:[{id:'old-id',name:'기존 운동',kg:35,reps:12,sets:4,memo:'1.0 기록 유지'}]}}};
assert.deepEqual(data.normalize(legacy).library,{상체:[],하체:[],기타:[]});assert.equal(data.normalize(legacy).days['2026-09-05'].exercises[0].memo,'1.0 기록 유지');
assert.throws(()=>data.parseBackup(JSON.stringify({format:'time-fitness-backup',version:99,data:legacy})));
const wrong=structuredClone(legacy);wrong.days['2026-02-30']=wrong.days['2026-09-05'];assert.throws(()=>data.normalize(wrong));
const server=http.createServer((req,res)=>{const f=path.join(assets,req.url==='/'?'index.html':req.url);if(!f.startsWith(assets+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(e,d)=>{if(e){res.writeHead(404).end();return;}res.setHeader('Content-Type',({'js':'application/javascript','html':'text/html','css':'text/css','jpg':'image/jpeg'})[f.split('.').pop()]||'application/octet-stream');res.end(d);});});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true});try{
const context=await browser.newContext({viewport:{width:372,height:913},hasTouch:true,acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const hold=async selector=>{
 if(selector.includes('data-hold=exercise')){await page.locator('#unlock').click();await page.locator('[data-edit="0"]').click();}
 else {if(!await page.locator('#viewer').isVisible())await page.locator(selector).first().click();await page.locator('#unlock').click();}
};
await page.goto(url);await page.locator('#splash').waitFor({state:'hidden'});const key=await page.locator('.day.today').getAttribute('data-day'),day=`[data-day="${key}"]`;
// No holding gesture may open the editor; tap opens the viewer only.
const initialDay=page.locator(day);await initialDay.scrollIntoViewIfNeeded();let box=await initialDay.boundingBox();await page.mouse.move(box.x+20,box.y+20);await page.mouse.down();await page.waitForTimeout(1250);assert.equal(await page.locator('#editor').isVisible(),false);await page.mouse.up();assert.equal(await page.locator('#viewer').isVisible(),true);const parsedDate=new Date(key+'T12:00:00');const expectedTitle=(parsedDate.getMonth()+1)+'월 '+parsedDate.getDate()+'일 '+['일','월','화','수','목','금','토'][parsedDate.getDay()]+'요일';assert.equal(await page.locator('#viewer-title').textContent(),expectedTitle);await page.locator('#unlock').click();assert.equal(await page.locator('#editor-title').textContent(),expectedTitle);assert.equal(await page.locator('[data-hold],#hold-progress').count(),0);await page.mouse.click(3,3);assert.equal(await page.locator('#editor').isVisible(),false);assert.equal(await page.locator('#viewer').isVisible(),true);await page.mouse.click(3,3);assert.equal(await page.locator('#viewer').isVisible(),false);
const firstKey=await page.locator('.day').first().getAttribute('data-day');assert.equal(new Date(firstKey+'T12:00:00').getDay(),0);await page.locator('[data-mode=month]').click();assert.deepEqual(await page.locator('.weekday').allTextContents(),['일','월','화','수','목','금','토']);assert.equal(await page.locator('.month .day').first().evaluate(el=>[...el.parentNode.children].indexOf(el)%7),new Date(parsedDate.getFullYear(),parsedDate.getMonth(),1).getDay());await page.locator('[data-mode=week]').click();
await hold(day);for(const group of ['상체','하체','기타']){await page.locator('[name=category]').selectOption(group);assert.equal(await page.locator('[name=exercise] option').count(),1);}
await page.locator('#new-name').click();await page.locator('[name=newName]').fill('나의 운동');await page.locator('#name-save').click();assert.equal(await page.locator('[name=exercise]').inputValue(),'나의 운동');await page.locator('[name=kind]').selectOption('pt');await page.locator('[name=kg]').fill('12.5');await page.locator('#add').click();
await page.locator('#new-name').click();await page.locator('[name=newName]').fill('추가 운동');await page.locator('#name-save').click();await page.locator('#add').click();await page.locator('#workout-form .save').click();if(!await page.locator('#viewer').isVisible())await page.locator(day).click();await page.locator('[data-memo="0"]').fill('저장하지 않은 메모');await page.locator('[data-close=viewer]').click();if(!await page.locator('#viewer').isVisible())await page.locator(day).click();assert.equal(await page.locator('[data-memo="0"]').inputValue(),'');await page.locator('[data-memo="0"]').fill('백업할 메모\n두 번째 줄');await page.locator('#memo-save').click();await page.reload();await page.locator('#splash').waitFor({state:'hidden'});if(!await page.locator('#viewer').isVisible())await page.locator(day).click();assert.equal(await page.locator('[data-memo="0"]').inputValue(),'백업할 메모\n두 번째 줄');await page.locator('[data-close=viewer]').click();
await hold(day);await page.locator('[name=category]').selectOption('기타');await page.locator('[name=exercise]').selectOption('나의 운동');await page.locator('#delete-name').click();assert.equal(await page.locator('[name=exercise] option').count(),2);await page.locator('[data-close=editor]').click();if(await page.locator('#viewer').isVisible())await page.locator('[data-close=viewer]').click();assert.equal(await page.locator(day+' .exercise-name').count(),2);
// Deleted library items must still be editable as historical exercises.
if(!await page.locator('#viewer').isVisible())await page.locator(day).click();await hold('[data-hold=exercise]');assert.equal(await page.locator('[name=category]').inputValue(),'기타');assert.equal(await page.locator('[name=exercise]').inputValue(),'나의 운동');await page.locator('[name=kg]').fill('25');await page.setViewportSize({width:690,height:803});assert.equal(await page.locator('[name=kg]').inputValue(),'25');await page.locator('#add').click();await page.locator('#workout-form .save').click();assert.equal(await page.locator('[data-memo="0"]').inputValue(),'백업할 메모\n두 번째 줄');await page.locator('[data-close=viewer]').click();
// Rename a catalog entry and its historical records without touching numeric values or notes.
await hold(day);assert.deepEqual(await page.locator('[name=category] option').allTextContents(),['상체','하체','기타']);assert.equal(await page.locator('[name=custom]').count(),0);await page.locator('[name=category]').selectOption('기타');await page.locator('[name=exercise]').selectOption('추가 운동');await page.locator('#rename-name').click();await page.locator('[name=newName]').fill('수정한 운동');await page.locator('#name-save').click();assert.equal(await page.locator('[name=exercise]').inputValue(),'수정한 운동');await page.locator('[data-close=editor]').click();if(await page.locator('#viewer').isVisible())await page.locator('[data-close=viewer]').click();if(!await page.locator('#viewer').isVisible())await page.locator(day).click();assert((await page.locator('.workout-head').nth(1).textContent()).includes('수정한 운동'));assert.equal(await page.locator('[data-memo="0"]').inputValue(),'백업할 메모\n두 번째 줄');assert.equal(await page.locator('.memo-label').first().evaluate(e=>[...e.childNodes].filter(n=>n.nodeType===3).map(n=>n.textContent.trim()).join('')),'');await page.locator('[data-close=viewer]').click();await page.reload();await page.locator('#splash').waitFor({state:'hidden'});assert((await page.locator(day).textContent()).includes('수정한 운동'));
// Add a library-only name; it must be included even without a calendar entry.
await hold(day);await page.locator('[name=category]').selectOption('상체');await page.locator('#new-name').click();await page.locator('[name=newName]').fill('목록에만 있는 운동');await page.locator('#name-save').click();await page.locator('[data-close=editor]').click();if(await page.locator('#viewer').isVisible())await page.locator('[data-close=viewer]').click();await page.locator('#settings-open').click();const downloadPromise=page.waitForEvent('download');await page.locator('#export-backup').click();const dl=await downloadPromise,backup=fs.readFileSync(await dl.path(),'utf8'),parsed=data.parseBackup(backup);assert.deepEqual(parsed.data.library.상체,['목록에만 있는 운동']);assert.equal(parsed.data.days[key].exercises[1].name,'수정한 운동');assert.equal(parsed.data.days[key].exercises[0].kg,25);assert.equal(parsed.data.days[key].exercises[0].memo,'백업할 메모\n두 번째 줄');await page.screenshot({path:path.join(out,'settings-unfolded.png')});
await page.locator('#import-file').setInputFiles({name:'restore.json',mimeType:'application/json',buffer:Buffer.from(backup)});await page.locator('#import-review').waitFor({state:'visible'});assert((await page.locator('#import-summary').textContent()).includes('운동명 2개'));await page.locator('#import-apply').click();assert.equal(await page.locator('#backup-status').textContent(),'가져왔습니다.');const stored=await page.evaluate(()=>localStorage.getItem('time-fitness-v1'));await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.waitForTimeout(100);assert.equal(await page.locator('#import-review').isVisible(),false);assert.equal(await page.evaluate(()=>localStorage.getItem('time-fitness-v1')),stored);
await page.mouse.click(3,3);assert.equal(await page.locator('#settings').isVisible(),false);await page.locator('#settings-open').click();await page.locator('#settings-title').click();assert.equal(await page.locator('#settings').isVisible(),true);
for(const width of [320,372,690,850]){await page.setViewportSize({width,height:Math.round(width*(width<600?2376/968:2160/1856))});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}assert.deepEqual(errors,[]);
// Native bridge: upgrading v1 records, export/import cancellation, restore, and write failure rollback.
const native=await browser.newContext({viewport:{width:372,height:913}});await native.addInitScript(legacy=>{if(!localStorage.getItem('initialized')){localStorage.setItem('native',JSON.stringify(legacy));localStorage.setItem('initialized','1');}window.fileResult='';window.Native={load:()=>localStorage.getItem('native'),save:s=>{if(window.failSave)return false;localStorage.setItem('native',s);return true;},exportBackup:s=>{window.exported=s;window.fileResult=JSON.stringify({kind:'export',content:''});return true;},importBackup:()=>{window.fileResult=JSON.stringify({kind:'cancel',content:''});},takeFileResult:()=>{const s=window.fileResult;window.fileResult='';return s;}};},legacy);const np=await native.newPage();await np.goto(url);await np.locator('#splash').waitFor({state:'hidden'});assert.equal(await np.locator('#storage-error').isVisible(),false);await np.locator('#settings-open').click();await np.locator('#export-backup').click();await np.waitForTimeout(600);assert.equal(await np.locator('#backup-status').textContent(),'백업 파일을 저장했습니다.');assert.equal(data.parseBackup(await np.evaluate(()=>window.exported)).data.days['2026-09-05'].exercises[0].memo,'1.0 기록 유지');await np.locator('#import-backup').click();await np.waitForTimeout(600);assert.equal(await np.locator('#backup-status').textContent(),'취소했습니다.');
await np.evaluate(text=>window.fileResult=JSON.stringify({kind:'import',content:text}),backup);await np.waitForTimeout(600);await np.evaluate(()=>window.failSave=true);await np.locator('#import-apply').click();assert((await np.locator('#backup-status').textContent()).includes('기존 데이터는 유지'));assert.equal(JSON.parse(await np.evaluate(()=>localStorage.getItem('native'))).days['2026-09-05'].exercises[0].memo,'1.0 기록 유지');await np.evaluate(()=>window.failSave=false);await np.locator('#import-apply').click();assert.equal(await np.locator('#backup-status').textContent(),'가져왔습니다.');
console.log('PASS: Sunday weekly/monthly alignment; date+weekday titles; no hold editing; one-tap editing; outside viewer/editor/settings close; inner clicks stay open; rename persists in library/history/restart/backup; memo label removed; three categories only; empty library; manual name/memo saves; custom entry; deletion preserves history; deleted-name editing; draft survives unfold; full backup/download/restore; invalid file rejected; v1 migration; Native file success/cancel/failure; restore rollback; responsive layouts; no JS errors.');fs.writeFileSync(path.join(out,'results.txt'),'All update checks passed.\n');await context.close();await native.close();
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});


